import coutureExperienceHero from "@/assets/projects/couture-experience/01-hero-couture-experience.png";
import tartaHero from "@/assets/projects/tarta-de-amor/01-hero.webp";
import mihnHero from "@/assets/projects/mihn/01-hero-home.webp";
import lillyHero from "@/assets/projects/lilly-breeze/01-home-hero.webp";
import sipHero from "@/assets/projects/sip/01-hero.webp";
import jorofHero from "@/assets/projects/jorof/01-hero.webp";
import noorixHero from "@/assets/projects/noorix/06-origin-hero.webp";
import pokemonHero from "@/assets/projects/pokemon-sa/01-hero-home.webp";
import pakmanHero from "@/assets/projects/pakman/01-hero.webp";
import circleSectionHero from "@/assets/projects/circle-section/01-hero.webp";
import opalStonesHero from "@/assets/projects/opal-stones/01-homepage-hero.webp";
import exEventsHero from "@/assets/projects/ex-events-exhibitions/01-hero.webp";
import firstAdvanceHero from "@/assets/projects/first-advance/01-hero-homepage.webp";

export const portfolioProjects = [
  {
    n: "01",
    t: "Couture Experience",
    slug: "couture-experience",
    cat: "Luxury Couture House",
    img: coutureExperienceHero,
    year: "2026",
    disciplines: "Identity, Creative Direction, Website",
    span: "full",
    ratio: "aspect-[21/9]",
  },
  {
    n: "02",
    t: "OPAL STONES",
    slug: "opal-stones",
    cat: "Luxury Brand Identity, UX/UI Design, Website Design, Front-end Craft, Content Direction",
    img: opalStonesHero,
    year: "2026",
    disciplines: "Luxury Identity, UX/UI, Website Design",
    span: "wide",
    ratio: "aspect-[16/10]",
  },
  {
    n: "03",
    t: "Circle Section",
    slug: "circle-section",
    cat: "Brand Identity, UX/UI Design, Web Design, Front-end Development, Content Direction",
    img: circleSectionHero,
    year: "2026",
    disciplines: "Brand Identity, UX/UI, Web Design, Front-end Development",
    span: "wide",
    ratio: "aspect-[16/10]",
  },
  {
    n: "04",
    t: "EX Events & Exhibitions",
    slug: "ex-events-exhibitions",
    cat: "UX/UI Design, Website Design, Brand Presence, Front-end Craft",
    img: exEventsHero,
    year: "2026",
    disciplines: "UX/UI, Website Design, Content Direction",
    span: "wide",
    ratio: "aspect-[16/10]",
  },
  {
    n: "05",
    t: "First Advance",
    slug: "first-advance",
    cat: "Brand Identity, Logo Design, UX/UI Design, Website Design, Front-end Craft",
    img: firstAdvanceHero,
    year: "2026",
    disciplines: "Logo Design, Brand Identity, UX/UI, Website Design",
    span: "wide",
    ratio: "aspect-[16/10]",
  },
  {
    n: "06",
    t: "Tarta De Amor",
    slug: "tarta-de-amor",
    cat: "Luxury Dessert Brand / Premium E-Commerce Experience",
    img: tartaHero,
    year: "2026",
    disciplines: "Brand Direction, E-Commerce UX/UI, Website",
    span: "wide",
    ratio: "aspect-[16/10]",
  },
  {
    n: "07",
    t: "SIP",
    slug: "sip",
    cat: "Saudi Beverage Brand",
    img: sipHero,
    year: "2026",
    disciplines: "Naming, Identity, Website",
    span: "wide",
    ratio: "aspect-[16/10]",
  },
  {
    n: "08",
    t: "NOORIX",
    slug: "norx-paints",
    cat: "Brand Identity and Website Experience",
    img: noorixHero,
    year: "2026",
    disciplines: "Naming, Identity, Website",
    span: "tall",
    ratio: "aspect-[3/4]",
  },
  {
    n: "09",
    t: "Lilly Breeze",
    slug: "lily-home-spa",
    cat: "Luxury Wellness Experience",
    img: lillyHero,
    year: "2026",
    disciplines: "Brand, Website",
    span: "small",
    ratio: "aspect-[4/3]",
  },
  {
    n: "10",
    t: "JOROF",
    slug: "jorof",
    cat: "Brand Identity, Creative Direction, UX/UI, Website Design",
    img: jorofHero,
    year: "2026",
    disciplines: "Identity, UX/UI, Website",
    span: "wide",
    ratio: "aspect-[16/10]",
  },
  {
    n: "11",
    t: "Pakman",
    slug: "pakman",
    cat: "Brand Identity, Website Design, Art Direction",
    img: pakmanHero,
    year: "2026",
    disciplines: "Identity, Packaging, Website",
    span: "wide",
    ratio: "aspect-[16/10]",
  },
  {
    n: "12",
    t: "Pokémon SA",
    slug: "pikmon-store",
    cat: "Collectibles E-Commerce Experience",
    img: pokemonHero,
    year: "2026",
    disciplines: "Identity, Commerce, UX/UI",
    span: "wide",
    ratio: "aspect-[16/10]",
  },
  {
    n: "13",
    t: "Mihn",
    slug: "mahn-platform",
    cat: "Employment Platform / UX/UI Experience",
    img: mihnHero,
    year: "2026",
    disciplines: "Employment UX/UI, Candidate Experience, Operations",
    span: "wide",
    ratio: "aspect-[4/3]",
  },
] as const;
